<#
.SYNOPSIS
Performs applicable health checks on the AD FS server (Proxy or STS)

.DESCRIPTION
The health checks generated by the Test-AdfsServerHealth cmdlet return a list of results with the following properties:
* Name : Mnemonic identifier for the test
* Result : One value of 'Pass','Fail','NotRun'
* Detail : Explanation of the 'Fail' and 'NotRun' result. It is typically empty when the check passes.
* Output : Data collected for the specific test. It is a list of Key value pairs
* ExceptionMessage: If the test encountered an exception, this property contains the exception message.

.PARAMETER VerifyO365
Boolean parameter that will enable Office 365 targeted checks. It is true by default.

.PARAMETER VerifyTrustCerts
Boolean parameter that will enable additional checks for relying party trust and claims provider trust certificates. It is false by default.


.EXAMPLE
Test-AdfsServerHealth | Where-Object {$_.Result -ne "Pass"}
Execute test suite and get only the tests that did not pass

.EXAMPLE
Test-AdfsServerHealth -VerifyOffice365:$false
Execute test suite in an AD FS farm where Office 365 is not configured

.EXAMPLE
Test-AdfsServerHealth -VerifyTrustCerts:$true
Execute test suite in an AD FS farm and examine the relying party trust and claims provider trust certificates

.NOTES
Most of the checks require executing AD FS cmdlets. As a result:
1. The most comprehensive analysis occurs when running from the Primary Computer in a Windows Internal Database farm.
2. For secondary computers in a Windows Internal Database farm, the majority of checks will be marked as "NotRun"
3. For a SQL Server farm, all applicable tests will run succesfully.
4. If the AD FS service is stopped, the majority of checks will be returned as 'NotRun'
#>
Function Test-AdfsServerHealth()
{
    [CmdletBinding()]
    Param
    (
        $verifyO365 = $true,
        $verifyTrustCerts = $false
    )

    $role = Get-ADFSRole

    if ($role -eq "STS")
    {
        TestAdfsSTSHealth -verifyO365 $verifyO365 -verifyTrustCerts $verifyTrustCerts
    }

    if ($role -eq "Proxy")
    {
        TestAdfsProxyHealth
    }
}